"use client";
import { useActionState, useState, useTransition } from "react";
import { useTranslations } from "next-intl";
import { enrollAction, verifyAction, type EnrollResult } from "@/app/[locale]/security/mfa/actions";

function CodeForm({ locale, factorId }: { locale: string; factorId: string }) {
  const t = useTranslations("mfa");
  const [state, action, pending] = useActionState(verifyAction, undefined);
  return (
    <form action={action} className="card">
      <input type="hidden" name="locale" value={locale} />
      <input type="hidden" name="factorId" value={factorId} />
      <label htmlFor="code">{t("code")}</label>
      <input id="code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" maxLength={7} required autoFocus />
      <button className="btn" style={{ width: "100%", marginTop: "1.25rem" }} disabled={pending}>{t("verify")}</button>
      {state?.error && <p className="error" role="alert">{t(state.error)}</p>}
    </form>
  );
}

export function MfaVerify({ locale, factorId }: { locale: string; factorId: string }) {
  return <CodeForm locale={locale} factorId={factorId} />;
}

export function MfaEnroll({ locale }: { locale: string }) {
  const t = useTranslations("mfa");
  const [res, setRes] = useState<EnrollResult | null>(null);
  const [pending, start] = useTransition();
  if (res?.ok) {
    return (
      <div className="card">
        <p>{t("scan")}</p>
        {/* QR is a data: SVG generated by Supabase; permitted by img-src data: */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={res.qr} alt="" width={200} height={200} style={{ background: "#fff", border: "2px solid var(--line)", borderRadius: 12 }} />
        <p className="eyebrow" style={{ marginTop: "1rem" }}>{t("key")}</p>
        <code style={{ wordBreak: "break-all" }}>{res.secret}</code>
        <CodeForm locale={locale} factorId={res.factorId} />
      </div>
    );
  }
  return (
    <div className="card">
      <button className="btn" disabled={pending} onClick={() => start(async () => setRes(await enrollAction()))}>{t("start")}</button>
      {res && !res.ok && <p className="error" role="alert">{t("rate")}</p>}
    </div>
  );
}
